version: '3'
services:
  db:
    image: postgres:10.5
    container_name: db-container
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mlflowdb
    volumes:
      - ../var/mlruns:/var/lib/postgresql/data:rw

  mlflow:
    build: .
    container_name: mlflow-container
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - LOCAL_UID=$LOCAL_UID #=1000 #$(id -u $USER)
      - LOCAL_GID=$LOCAL_GID #=1000 #$(id -g $USER)
      - WORKING_DIR=$WORKING_DIR #=${PWD}/..
      - ARTIFACT_DIR=$ARTIFACT_DIR #=${PWD}/../artifact
      - DB_URI=postgresql://postgres:postgres@db:5432/mlflowdb #${PWD}
    volumes:
      - ${WORKING_DIR}:${WORKING_DIR}


